#name of the workflow
name: CI Demo 

# define when the action should be triggered is specified in this block
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# define the actions to be performed is specified in this block
jobs:
  build:
    runs-on: windows-latest 
  
    steps:
    - uses: actions/checkout@v2
  
    - name: Run a one-line script
      run: echo Hello CI!
    
    - name: Run a multi-line script
      run:
        echo Add other actions to build,
        echo test, and deploy your projct.   


